### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by olexandrduplava** [olexandrduplava/homepage#5]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by UselessAlex** [comment]
Ex-president, dude with over a lot of money, I wear meme hair on my head.

**Comment by olexandrduplava** [comment]
Yeah boooooooyyyyyyyyyyyyyyyyyy
