### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by olexandrduplava** [olexandrduplava/homepage#8]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by UselessAlex** [comment]
I'm too lazy for writing A LONG STORY cuz it's 00:04 4th May and i just started do this tasks 2 hours ago so be kind to me :)

Just write one MEME - GOT BANNED ON TWITTER XD
